# Generated by Django 5.2 on 2025-04-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('descripcion', models.TextField()),
                ('ingredientes', models.JSONField()),
                ('preparacion', models.TextField()),
            ],
        ),
    ]
