# Generated by Django 5.2 on 2025-04-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saboresDeCine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='pelicula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
