# Generated by Django 5.2 on 2025-04-12 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saboresDeCine', '0003_favoritocomida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoDecoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('decoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='saboresDeCine.ideadecoracion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_decoracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'decoracion')},
            },
        ),
    ]
