# Generated by Django 5.2 on 2025-04-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saboresDeCine', '0003_pelicula_receta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recomendacion',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receta',
            name='peliculas',
            field=models.ManyToManyField(blank=True, to='saboresDeCine.pelicula'),
        ),
    ]
