# Generated by Django 5.2 on 2025-04-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saboresDeCine', '0004_delete_recomendacion_alter_pelicula_fecha_estreno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
            ],
        ),
    ]
