# Generated by Django 5.2 on 2025-04-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saboresDeCine', '0006_mensajecontacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajecontacto',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mensajecontacto',
            old_name='fecha_envio',
            new_name='fecha',
        ),
    ]
