# Generated by Django 5.2 on 2025-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saboresDeCine', '0007_rename_correo_mensajecontacto_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPrivacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Política de Privacidad', max_length=200)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
